# syntax=docker/dockerfile:1

# Use the same Ruby version as your project
ARG RUBY_VERSION=3.2.3
FROM ruby:$RUBY_VERSION-slim

# Set environment variables for development
ENV RAILS_ENV=development \
    BUNDLE_WITHOUT="production" \
    LANG=C.UTF-8

# Install essential packages
# ADDED libpq-dev to build the 'pg' gem
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    postgresql-client \
    libpq-dev \
    nodejs \
    yarn \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /rails

# Copy Gemfiles and install dependencies
COPY Gemfile Gemfile.lock ./
RUN bundle config set force_ruby_platform true
RUN bundle install

# Copy the rest of the application code into the container
COPY . .

# Expose port 3000 to the host
EXPOSE 3000